services:
  social-network-database:
    container_name: social-network-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcdefg
      - POSTGRES_DB=social_network_database
    ports:
      - 5432:5432
    volumes:
      - cash-track-database-volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  cash-track-database-volume:
